### ISSUE TITLE
Not really an Issue so to speak but maybe possible feature request or help making a Arch pkgbuild for pacman?

### ISSUE THREAD

**Issue by tetoNidan** [saieno/scuf-controller#1]
I just bought a scruf controller and is in the mail. I forgot to search compatibility before buying it. Searching linux scruf led me to you.

So I don't even know if this is needed as PS5 dualsence support has been added to the kernel but I was wondering if you would be interested in making a pkgbuild file for Arch if the controller ends up not working? So it's in the mail and should be here in a week or so and I can test if it has OTB support and get back to you. That is if your interested? If not would you mind me picking your brain about how this reop works so I could attempt it? 

Thanks for your time.

**Comment by saieno** [comment]
Heya!

So this particular service relies on xboxdrv, which I know is no longer on RedHat distros and I'm not sure if its available on Arch distros as well. I most likely won't make a Arch version but I can help explain what is going on with the service if needed. Everything that is required is freely available within the repo and could be adapted manually for your needs.

Its certainly possible you may not need it of course and your controller will work as expected. But I made this because the SCUF controller, while identified, wouldn't have the correct button mapping while in-game and there was no way to change it.

Thanks!

**Comment by tetoNidan** [comment]
Hay thanks, I guess it'll ship out on December 1. I'll give it a test and see about OTB experience.

>I can help explain what is going on with the service if needed

Thanks, I just might need that!

The AUR still supports `xboxdrv` so at least that is covered. I will give it a test and report back even if it works OTB. That way you know what's coming down the pipe to debain eventually. 

Thanks saieno

**Comment by saieno** [comment]
Heya @tetoNidan just thought I'd check in and see if you needed any further assistance with the new controller.

**Comment by tetoNidan** [comment]
I should be getting the controller later tonight maybe tomorrow. Probably tonight according to UPS. I'll defiantly check it out and get back to you. Thank you once again. I do appreciate the help and I promise I will let you know whats going on even if it works OTB!

**Comment by tetoNidan** [comment]
Hi [saieno](https://github.com/saieno), I just received the controller. It looks like it will work out of the box. It should have no real problems connecting via bluetooth for most people.

I have a rare issue where I have to pair the controller, the controller will appear to be paired but when starting the controller the controller will flash then turn off. This can be fixed by booting into a different kernel. Once you boot to a different kernel the controller pairs just fine. I have to do the same thing with my PS5 DualSense controller. Might be an issue with `bluez` or `bluetoothctl`. I will likely start searching for this particular bug to see if there is any other solution or if I need to file a bug report. Hopefully I can diagnose where the issue is coming from.

Paring to bluetooth recognizes the controller as any other DualSense controller. I don't anticipate any real issues although I have not done any real gaming yet. The controller is very low on battery but on my first small test the trackpad, D pad and left joystick all worked. I'm betting that everything will work. I'm hopeful that steam will let me independently assign the paddle buttons on the back but wont be disappointed if I cant!

Once again I really appreciate you being willing to help me out adapting your work! Is it alright if I keep this issue open till later tonight maybe tomorrow so I can test everything out? I promise I'll update you as soon as I know.

**Comment by saieno** [comment]
No problem at all @tetoNidan! The issues I ran into weren't the controller being recognized as a Dualshock 4 controller when the game supports Dualshock 4 controllers natively. The issue I ran into is when it doesn't support PS4 controllers and mainly supports Xbox 360 and Xbox One controllers, then the face buttons (X generally being A, O being B, etc) wouldn't be mapped correctly.

There's no rush at all and feel free to do all the testing you need to feel comfortable with the controller.

**Comment by tetoNidan** [comment]
So I tested BG3 which I think has native support, FO4 which I think has xbox layout and CP2077 which has limited controller support. I don't have any non steam games so I don't know how the controller would behave outside of steam.

With my limited testing I think everything is working as expected! 

Thanks once again [saieno](https://github.com/saieno), I do appreciate your willingness to help! I'm going to close this and consider this a successful native OTB controller, at least running through steam.

**Comment by nonetrix** [comment]
Got my controller from the closet, honestly not sure why I didn't use it much but that's beside the point. Would also like a Nix package, is there a better way to get my controller to work? I am confused as to why it doesn't just work out of the box, how is it different from a normal DualShock? It works somewhat in that I can give inputs to a game but the controls are all messed up and the right stick is constantly being pressed upper left, weirdly the triggers seem to influence the sticks it's all kinds of messed up. I haven't tried bluetooth but I am not even going to bother with how complete garbage the state of Bluetooth is on Linux, it never works for me well even for the most basic things like Bluetooth headphones. I feel like a kernel patch should be made for this controller maybe, handling it like this just seems hacky at best. Maybe also some manual install instructions could help, but with NixOS that isn't enough

**Comment by saieno** [comment]
> It works somewhat in that I can give inputs to a game but the controls are all messed up and the right stick is constantly being pressed upper left, weirdly the triggers seem to influence the sticks it's all kinds of messed up.

The source is available if you'd like to replicate the setup. The deb specific nature is just for installing the scripts in the correct places and the systemd targets.
